### ISSUE TITLE
Cannot find module "dateformat"

### ISSUE THREAD

**Issue by Booteille** [ManrajGrover/organize-cli#25]
Hi!

The dateformat module seems to be required in order to use organize-cli but organize-cli does not install it by default.
I had this issue when performing `organize -s ./ -o output`:
```console
module.js:487
    throw err;
    ^

Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/organize-cli/dist/helpers.js:6:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Everything worked well once I installed globally the dateformat module.

**Comment by ManrajGrover** [comment]
Hi, thanks for reporting this. 😄  Please share the node version so that I can debug this.

**Comment by Booteille** [comment]
I am on nodejs 8.1.4 and npm 5.3.0.

**Comment by ManrajGrover** [comment]
@Booteille Please try re-installing now i.e. `npm install -g organize-cli@0.5.8`

**Comment by Booteille** [comment]
Seems to be fixed! Thank you!
